# -*- coding: utf-8 -*-
"""GC_content _multiple_FASTA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ew6-HI20SOk1E1j8UtvorztqK2TKoGHO

Following is the code to read multiple fasta files from a directory and calculate the GC content of individual file, and store the name of organism along with its corresponding GC content in a data frame.
"""

pip install Bio

from Bio import SeqIO
from Bio.SeqUtils import gc_fraction
import pandas as pd
import glob
import os

folder="/content/Fasta files"

fasta_files=glob.glob('%s/*.fasta'%folder)

strain=[]
gc_list=[]

def gc_content(fasta):
  file_obj=SeqIO.read(fasta,'fasta')
  sequence=file_obj.seq

  gc_cont=gc_fraction(sequence)

  gc_cont=round(gc_cont,2)
  filename=os.path.split(fasta)
  filename=filename[1]
  filename=filename.strip('.fasta')

  strain.append(filename)
  gc_list.append(gc_cont)

for fasta in fasta_files:
  gc_content(fasta)

print(strain)

print(gc_list)

df=pd.DataFrame()


df['Strain_name']=strain
df['GC_content']=gc_list

df.head()

output="/content/Fasta files/strain_GC_csv"

df.to_csv(output, index=False)

