# -*- coding: utf-8 -*-
"""list_comphrension.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dshb3CK8E4yAyWKITFI8SNQEydBfKw5Q
"""

cities=["Ahemdabad","Gandhinagar","Shimla","Pune","Mumbai","Nashik","Raipur","Indore","Guwahati","Srinagar","Bengaluru"]

cities_a=[x for x in cities if x != "Pune"]

print(cities_a)

new_list=[x for x in range(20) if x <= 13]

print(new_list)

#Sets the value for entries in newlist

cities_lower=[x.lower() for x in cities]

print(cities_lower)

#cities_sort=[x.() for x in cities]

#print(cities_sort)

newlist = [x if x != "Shimla" else "Itanagar" for x in cities]

print(newlist)

